development:
  adapter: postgresql
  encoding: utf8
  database: boda_development
  pool: 5
  username: postgres
  password: isabel2005

production:
  adapter: postgresql
  encoding: utf8
  database: boda_production
  pool: 5
  username: boda4
  password: enriqueybea